version: "3"

services:
  mysqldb:
    container_name: mysqldb
    image: mysql:8
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=tpachato
      - MYSQL_ROOT_PASSWORD=admin
    volumes:
      - /home/mysqll:/var/lib/mysql  
  spring_app:
    image: achatt
    container_name: confident_torvalds
    restart: on-failure
    environment:
        - spring.datasource.url=jdbc:mysql://mysqldb/tpachato?createDatabaseIfNotExist=true    
        - 9090:8089 
    depends_on:
     - mysqldb
